# HYPERPARAMETERS
DICE_PER_PLAYER = 5
N_PLAYERS = 3
TOTAL_DICE = DICE_PER_PLAYER * N_PLAYERS
FACE_COUNT = 6
NUM_ACTIONS = 1 + TOTAL_DICE * FACE_COUNT

BASE = 10   # for encoding purposes
MAX_BID_Q = TOTAL_DICE
BELIEF_Q_MAX = TOTAL_DICE
BELIEF_Q_CAP = 15
