# HYPERPARAMETERS

# DO NOT CHANGE VALUES AFTER STARTING BOT TRAINING
DICE_PER_PLAYER = 5
MAX_PLAYERS = 3
MAX_OPPONENTS = MAX_PLAYERS - 1
TOTAL_DICE = DICE_PER_PLAYER * MAX_PLAYERS
FACE_COUNT = 6
NUM_ACTIONS = 1 + TOTAL_DICE * FACE_COUNT
MAX_STATE_DIM = 1 + 1 + FACE_COUNT + 2 + (MAX_OPPONENTS * FACE_COUNT) + 1

BASE = 10   # for encoding purposes
MAX_BID_Q = TOTAL_DICE
BELIEF_Q_MAX = TOTAL_DICE
BELIEF_Q_CAP = 15

# Opponent modeling
OPPONENT_FEATURE_DIM = MAX_OPPONENTS * FACE_COUNT
NON_OPPONENT_FEATURE_DIM = MAX_STATE_DIM - OPPONENT_FEATURE_DIM

DRON_MOE_NUM_EXPERTS = 3
DRON_MOE_HIDDEN = 128
DRON_MOE_GATE_HIDDEN = 64