# HYPERPARAMETERS
DICE_PER_PLAYER = 5
N_PLAYERS = 4
TOTAL_DICE = DICE_PER_PLAYER * N_PLAYERS

BASE = 10   # for encoding purposes
FACE_COUNT = 6 # die faces 1-6 (0 is no die)
MAX_BID_Q = TOTAL_DICE # max quantity in a bid
BELIEF_Q_MAX = TOTAL_DICE
BELIEF_Q_CAP = 15